version: '3'

services:
  php:
    #image: php:7.2-apache <- DockerFileで読み込んでいるのでいらない(buildセクションで行っている)
    volumes:
      - ./src:/var/www/html
    ports:
      - 5050:80
    links:
      - mysql
    container_name: phpstudy-php7.4
    build:
      context: ./php
      dockerfile: Dockerfile
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: phpstudy-mysql
    ports:
      - 33006:33006
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    container_name: phpstudy-phpMyAdmin
